### ISSUE TITLE
MultipartRequest

### ISSUE THREAD

**Issue by kamim0227** [2021-SMHRD-KDT-AI-1/p1j4#27]
MultipartRequest 사용하여 request.getPrarmeter로 가지고 올 경우 값이 안넘어옵니다.ㅡㅜ

**Comment by Koth100** [comment]
form 태그에서 enctype="multipart/form-data" 속성을 사용했다면 서블릿에서 request.getParameter를 이용해 확인할 수 없음.
MultipartRequest 객체를 생성해 해당 객체를 통해 getParameter를 사용해야함

참고사이트 : http://blog.naver.com/PostView.nhn?blogId=software705&logNo=220551397421
